



<!-- MAXCDN for carousel -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<!--rafael css browser selector -->
<script src="<?php echo $js;?>rafael.js" type="text/javascript"></script>

<!-- Main -->
<script type="text/javascript" src="<?php echo $js;?>jquery-3.6.0.min.js"></script>
<script src="<?php echo $js;?>bootstrap.min.js"></script>
<script type="text/javascript" src= "<?php echo $js;?>front.js"></script>


<script src="https://apis.google.com/js/api:client.js"></script>




</body>
</html>
