<html>
<head>
		<meta charset="utf-8">
		<meta name="robots" content="noindex">
		<title><?php echo $title;?></title>
		<link rel="stylesheet" type="text/css" href="<?php echo $css;?>bootstrap.min.css">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
		<link rel="stylesheet" type="text/css" href="<?php echo $css;?>backStyle.css">
</head>
<body>



